apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-be

resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- prometheusrule.yaml
- externalsecret-playit.yaml
- deployment-playit.yaml
- ciliumnetworkpolicy-playit.yaml
